language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install PySide --no-index --find-links http://parkin.github.io/python-wheelhouse/
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install

script:
  - flake8 TrivialUI
  - nosetests

