language: python

addons:
  apt:
    packages:
      libqt4-dev

install:
  - pip install -r requirements.txt
  - pip install PySide --no-index --find-links http://parkin.github.io/python-wheelhouse/
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install

script: nosetests

